//
// Generated file, do not edit! Created by nedtool 5.6 from attacks/controlmessages/delayAttack/NTU_DelayMessage.msg.
//

#ifndef __NTU_DELAYMESSAGE_M_H
#define __NTU_DELAYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>attacks/controlmessages/delayAttack/NTU_DelayMessage.msg:1</tt> by nedtool.
 * <pre>
 * message NTU_DelayMessage
 * {
 *     double delayAttackProbability; // Attack probability
 * }
 * </pre>
 */
class NTU_DelayMessage : public ::omnetpp::cMessage
{
  protected:
    double delayAttackProbability;

  private:
    void copy(const NTU_DelayMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NTU_DelayMessage&);

  public:
    NTU_DelayMessage(const char *name=nullptr, short kind=0);
    NTU_DelayMessage(const NTU_DelayMessage& other);
    virtual ~NTU_DelayMessage();
    NTU_DelayMessage& operator=(const NTU_DelayMessage& other);
    virtual NTU_DelayMessage *dup() const override {return new NTU_DelayMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getDelayAttackProbability() const;
    virtual void setDelayAttackProbability(double delayAttackProbability);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NTU_DelayMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NTU_DelayMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NTU_DELAYMESSAGE_M_H

