//
// Generated file, do not edit! Created by nedtool 5.6 from attacks/controlmessages/wormholeAttack/NTU_WormholeMessage.msg.
//

#ifndef __NTU_WORMHOLEMESSAGE_M_H
#define __NTU_WORMHOLEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>attacks/controlmessages/wormholeAttack/NTU_WormholeMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message NTU_WormholeMessage
 * {
 *     double wormholeAttackProbability;
 * }
 * </pre>
 */
class NTU_WormholeMessage : public ::omnetpp::cMessage
{
  protected:
    double wormholeAttackProbability;

  private:
    void copy(const NTU_WormholeMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NTU_WormholeMessage&);

  public:
    NTU_WormholeMessage(const char *name=nullptr, short kind=0);
    NTU_WormholeMessage(const NTU_WormholeMessage& other);
    virtual ~NTU_WormholeMessage();
    NTU_WormholeMessage& operator=(const NTU_WormholeMessage& other);
    virtual NTU_WormholeMessage *dup() const override {return new NTU_WormholeMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual double getWormholeAttackProbability() const;
    virtual void setWormholeAttackProbability(double wormholeAttackProbability);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NTU_WormholeMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NTU_WormholeMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NTU_WORMHOLEMESSAGE_M_H

