//
// Generated file, do not edit! Created by nedtool 5.6 from attacks/controlmessages/grayholeAttack/NTU_GrayholeMessage.msg.
//

#ifndef __NTU_GRAYHOLEMESSAGE_M_H
#define __NTU_GRAYHOLEMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>attacks/controlmessages/grayholeAttack/NTU_GrayholeMessage.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * message NTU_GrayholeMessage
 * {
 *     bool grayOnlyWhenRouteInTable;
 *     // TRUE indicates that only RREQ for routes that are in routing table are answered as the best route across the sink node.
 *     // A false value indicates that all the sinkhole node will answer to all the RREQ with fake routes. 
 *     double grayholeAttackProbability;  	//Probability for announcing a fake route when a RREQ is received. Value in [0,1]
 *     double seqnoAdded; 					// Sequence number.
 *     int numHops;
 * }
 * </pre>
 */
class NTU_GrayholeMessage : public ::omnetpp::cMessage
{
  protected:
    bool grayOnlyWhenRouteInTable;
    double grayholeAttackProbability;
    double seqnoAdded;
    int numHops;

  private:
    void copy(const NTU_GrayholeMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const NTU_GrayholeMessage&);

  public:
    NTU_GrayholeMessage(const char *name=nullptr, short kind=0);
    NTU_GrayholeMessage(const NTU_GrayholeMessage& other);
    virtual ~NTU_GrayholeMessage();
    NTU_GrayholeMessage& operator=(const NTU_GrayholeMessage& other);
    virtual NTU_GrayholeMessage *dup() const override {return new NTU_GrayholeMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual bool getGrayOnlyWhenRouteInTable() const;
    virtual void setGrayOnlyWhenRouteInTable(bool grayOnlyWhenRouteInTable);
    virtual double getGrayholeAttackProbability() const;
    virtual void setGrayholeAttackProbability(double grayholeAttackProbability);
    virtual double getSeqnoAdded() const;
    virtual void setSeqnoAdded(double seqnoAdded);
    virtual int getNumHops() const;
    virtual void setNumHops(int numHops);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const NTU_GrayholeMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, NTU_GrayholeMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __NTU_GRAYHOLEMESSAGE_M_H

